In [1]:
# BASIC NUMPY ARRAYS
import numpy as np

In [10]:
# attributes of np array such as ndim, shape, size, dtype
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(2,4,3))
print(x1.ndim, x1.shape, x1.size, x1.dtype)
print(x2.ndim, x2.shape, x2.size, x2.dtype)
print(x3.ndim, x3.shape, x3.size, x3.dtype)

1 (6,) 6 int64
2 (3, 4) 12 int64
3 (2, 4, 3) 24 int64


In [11]:
# other attributes of np array , itemsize = lists the size (in bytes) of each array element
#                               nbytes = which lists the total size(in bytes) of the array
x2.itemsize, x2.nbytes

(8, 96)

In [17]:
# Array Indexing 
# Accessing single element
print(x1[0], x1[-1])
x1[0] = 3.14
print(x1)

# In Multidimensional array, access element using a tuple ',' seperated
print(x3[0,0,2])
print(x2[0,0])

3 6
[3 4 4 4 1 6]
6
9


In [20]:
# array slicing ;- accessing subarrays ( x[start: stop: step] )
x = np.arange(10)
print(x[:5])
print(x[5:])
print(x[4:7])
print(x[::2])

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]


In [24]:
# accessing multi dimensional array
print(x2[:2, :3])

# sub array of 2*2 from x2
print(x2)
x2_sub = x2[:2,2:]
print(x2_sub)

[[9 3 9]
 [0 6 9]]
[[9 3 9 8]
 [0 6 9 5]
 [1 1 3 4]]
[[9 8]
 [9 5]]


In [25]:
# creating copy of array, if you create sub array then changes in sub array will also effect the main array but copy will create a seperate array and changes in sub array will not effect the main array
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[9, 3],
       [0, 6]])

In [36]:
# reshaping of array
# grid = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
grid = np.arange(1,10).reshape((3,3))
print(grid)
np.arange(1,17).reshape(4,4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# concatenation of arrays , np.concatenate, np.vstack, np.hstack
print(np.concatenate([x1,x]))
print(x3)
np.vstack(x3)

[3 4 4 4 1 6 0 1 2 3 4 5 6 7 8 9]
[[[7 8 6]
  [8 9 3]
  [7 2 8]
  [9 8 2]]

 [[3 1 1]
  [0 1 7]
  [9 7 1]
  [3 6 9]]]


array([[7, 8, 6],
       [8, 9, 3],
       [7, 2, 8],
       [9, 8, 2],
       [3, 1, 1],
       [0, 1, 7],
       [9, 7, 1],
       [3, 6, 9]])

In [53]:
# splitting arrays, np.split, np.hsplit, np.vsplit
print("x = ",x)
xa, xb, xc = np.split(x, [3,5])
xa, xb, xc

x =  [0 1 2 3 4 5 6 7 8 9]


(array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9]))