In [1]:
import numpy as np

In [6]:
# List to array
list_data = [1,2,3,4,5,6,9,3]
print(np.array([3.14, 1, 3.4, 5]))
print(np.array(list_data))

[3.14 1.   3.4  5.  ]
[1 2 3 4 5 6 9 3]


In [5]:
# Specifying data of array
print(np.array(list_data, dtype="float32"))
print(np.array(list_data, dtype="bool"))

[1. 2. 3. 4. 5. 6. 9. 3.]
[ True  True  True  True  True  True  True  True]


In [10]:
# Nested list result in multi-dimensional array
np.array([range(i,i+7) for i in range(2,6)])

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11]])

In [17]:
### Creating Array From Scratch

# Array containing Zeros only
print(np.zeros(10, dtype="int"))
print(np.zeros((3,4), dtype="float32"))

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [63]:
# cretate a 3*5 floating point array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# create a 3*5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# create a array of five values evenly spaced between two numbers
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# create array filled with a linear sequence start=0 , end=20 and stepping =2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# create 3*3 array of uniformaly distributed random values b/w 0&1
np.random.random((3,3))

array([[0.55311366, 0.31782966, 0.23576819],
       [0.57576996, 0.87571231, 0.78454258],
       [0.10688291, 0.11348455, 0.65843786]])

In [54]:
# create 3*3 array of normally distrubuted random values with mean 0 and standard deviation 1
data = np.random.normal(0,1,(3,3))
print(data)
print(data[0].std())
print(data.std())

[[ 1.45779457 -0.02214976  1.04204867]
 [-0.1826704   1.07227391  0.19119282]
 [ 0.4494098  -1.27817897  0.18939192]]
0.6232172917449824
0.7714339796269312


In [57]:
# create a 3*3 array of random integers in the interval [0,10)
np.random.randint(0,10,(3,3))

array([[7, 4, 6],
       [4, 4, 8],
       [2, 0, 8]])

In [59]:
# create 3*3 identity matrix
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
# create an uninitiallized array of three integer
np.empty(3)

array([1., 1., 1.])