In [1]:
import numpy as np 

In [14]:
# Arrays Broadcasting
# -> broadcasting is simply a set of rules for applying binary ufuncs (eg. addition, subtraction, multiplication etc) on arrays of different sizes

x = np.array([0,1,2,3])
x+5

# [0,1,2,3]+[5]
# --------------
# [0,1,2,3]
# [5,5,5,5]
# -------------
# [5,6,7,8]
# -------------


array([5, 6, 7, 8])

In [13]:
m = np.ones((3,4))
print(m+x)

# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]] + [0,1,2,3]
# ---------------
#  [[1. 1. 1. 1.]  + [[0,1,2,3]
#   [1. 1. 1. 1.]  +  [0,1,2,3]
#   [1. 1. 1. 1.]] +  [0,1,2,3]]
# ----------------
# [[1. 2. 3. 4.]
#  [1. 2. 3. 4.]
#  [1. 2. 3. 4.]]
# ---------------

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [19]:
x.reshape(1,4)

array([[0, 1, 2, 3]])

In [30]:
# Comparision, Masks and Boolean logic
print("Mask  = ",x<2)

# counting entries
# -> count the no of True entries in boolean array
print("Non Zero count = ",np.count_nonzero(x<2))

# We can use sum method as well as True means 1 and false means 0
print("nonzero using sum method = ", np.sum(x<2))

# any and all
print("all less then 10 = ", np.all(x<10))

Mask  =  [ True  True False False]
Non Zero count =  2
nonzero using sum method =  2
all less then 10  True


In [34]:
# boolean operations
x = np.random.randint(1,100, size=40)
print("x = ", x)
print(np.sum((x > 40) & (x <60)))

x =  [24 37 23 14 83 17 12 44 96 98 48 59  3 36 83 50 87 35 95 46 37 18 54  3
 18 47 28 79 44 81  1 21 94 32 58 13 73 48 88 94]
10


In [43]:
matrix = np.matrix([[1,2,3],[4,5,6]])
print(matrix[0,:2])

[[1 2]]
