In [1]:
import numpy as np 

In [7]:
# Ufunc in numpy
# operations linke +, -, / , * , // , ** , % can be performed on numpy arrays for fast computation
x1 = np.arange(5)
x2 = np.arange(1,6)
print(x1 , x2)
x3 = x1*x2
x3

[0 1 2 3 4] [1 2 3 4 5]


array([ 0,  2,  6, 12, 20])

In [11]:
# We have corrosponding methods in numpy , like add(), subtract() etc
print(np.add(x1,x2))
print(np.floor_divide(x1,x2))
print(np.subtract(x1,x2))

[1 3 5 7 9]
[0 0 0 0 0]
[-1 -1 -1 -1 -1]


In [12]:
# we can use np.abs() or np.absolute()
np.abs(np.subtract(x1,x2))

array([1, 1, 1, 1, 1])

In [13]:
# Trigonometric functions in numpy
theta = np.linspace(0, np.pi, 3)
print("Theta values = ", theta)
print("sin = ", np.sin(theta))
print("cos = ", np.cos(theta))
print("tan = ", np.tan(theta))

Theta values =  [0.         1.57079633 3.14159265]
sin =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
# Inverse Trigonometric functions in numpy
np.arcsin(theta), np.arccos(theta), np.arctan(theta)

(array([ 0., nan, nan]),
 array([1.57079633,        nan,        nan]),
 array([0.        , 1.00388482, 1.26262726]))

In [19]:
# Exponents and logarithms in numpy
x = [1,2,3]
print("e^x = ", np.exp(x))  # e^x
print("2^x = ", np.exp2(x))
print("n^x = ", np.power(3, x))

# logs
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
n^x =  [ 3  9 27]
[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


In [21]:
x = [0, 0.001, 0.0001, 0.1]
print(np.expm1(x))
print(np.exp(x))

[0.00000000e+00 1.00050017e-03 1.00005000e-04 1.05170918e-01]
[1.         1.0010005  1.00010001 1.10517092]


In [25]:
#  Specifying Output in arrays
x = np.arange(5)
y = np.arange(5)
print("y = ",y)
np.multiply(x, 10, out=y)
print("y = ",y)
y = np.zeros(10)
np.power(2,x, out=y[::2])
print("y = ",y)

y =  [0 1 2 3 4]
y =  [ 0 10 20 30 40]
y =  [ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [31]:
# Aggregates
x = np.arange(1,6)
print("Reduced x addition = ",np.add.reduce(x))
print("multiply all elements of x (reduce) = ", np.multiply.reduce(x))

Reduced x addition =  15
multiply all elements of x (reduce)  120


In [32]:
# to store all the intermediate results of computation , we can use accumulate() , cf
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [38]:
print("sum of elements  =       ", np.sum(x))
print("product =                ", np.prod(x))
print("mean =                   ", np.mean(x))
print("standard deviation =     ", np.std(x))
print("variance =               ", np.var(x))
print("minimum =                ", np.min(x))
print("maximum =                ", np.max(x))
print("index of min =           ", np.argmin(x))
print("index of max =           ", np.argmax(x))
print("median =                 ", np.median(x))
print("any value true =         ", np.any(x))
print("all value true =         ", np.all(x))

sum of elements  =        15
product =                 120
mean =                    3.0
standard deviation =      1.4142135623730951
variance =                2.0
minimum =                 1
maximum =                 5
index of min =            0
index of max =            4
median =                  3.0
any value true =          True
all value true =          True
